"""
Configuração de fixtures globais para testes
"""

import tempfile
import zipfile
from io import BytesIO
from pathlib import Path
from unittest.mock import Mock, patch

import pytest


@pytest.fixture
def sample_xml_content():
    """Retorna conteúdo XML de exemplo"""
    return """
    <?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
    <CURRICULO-VITAE SISTEMA-ORIGEM-XML="LATTES_OFFLINE" NUMERO-IDENTIFICADOR="1041420694737077" DATA-ATUALIZACAO="03072020" HORA-ATUALIZACAO="221236">
        <DADOS-GERAIS NOME-COMPLETO="Mariana Cordeiro da Costa" NOME-EM-CITACOES-BIBLIOGRAFICAS="COSTA, M. C." NACIONALIDADE="B" PAIS-DE-NASCIMENTO="Brasil" UF-NASCIMENTO="" CIDADE-NASCIMENTO="" PERMISSAO-DE-DIVULGACAO="NAO" DATA-FALECIMENTO="" SIGLA-PAIS-NACIONALIDADE="BRA" PAIS-DE-NACIONALIDADE="Brasil" ORCID-ID="">
            <RESUMO-CV TEXTO-RESUMO-CV-RH="Estudante do 4º período de Turismo pela Universidade Federal Fluminense." TEXTO-RESUMO-CV-RH-EN=""/>
            <ENDERECO FLAG-DE-PREFERENCIA="ENDERECO_RESIDENCIAL">
                <ENDERECO-PROFISSIONAL CODIGO-INSTITUICAO-EMPRESA="" NOME-INSTITUICAO-EMPRESA="" CODIGO-ORGAO="" NOME-ORGAO="" CODIGO-UNIDADE="" NOME-UNIDADE="" LOGRADOURO-COMPLEMENTO="" PAIS="" UF="" CEP="" CIDADE="" BAIRRO="" DDD="" TELEFONE="" RAMAL="" FAX="" CAIXA-POSTAL="" HOME-PAGE=""/>
            </ENDERECO>
            <FORMACAO-ACADEMICA-TITULACAO>
                <GRADUACAO SEQUENCIA-FORMACAO="2" NIVEL="1" TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO="" NOME-DO-ORIENTADOR="" CODIGO-INSTITUICAO="000500000000" NOME-INSTITUICAO="Universidade Federal Fluminense" CODIGO-ORGAO="" NOME-ORGAO="" CODIGO-CURSO="60092360" NOME-CURSO="Turismo" CODIGO-AREA-CURSO="" STATUS-DO-CURSO="EM_ANDAMENTO" ANO-DE-INICIO="2018" ANO-DE-CONCLUSAO="" FLAG-BOLSA="NAO" CODIGO-AGENCIA-FINANCIADORA="" NOME-AGENCIA="" NUMERO-ID-ORIENTADOR="" CODIGO-CURSO-CAPES="83009" TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO-INGLES="" NOME-CURSO-INGLES="" FORMACAO-ACADEMICA-TITULACAO="" TIPO-GRADUACAO="N" CODIGO-INSTITUICAO-GRAD="" NOME-INSTITUICAO-GRAD="" CODIGO-INSTITUICAO-OUTRA-GRAD="" NOME-INSTITUICAO-OUTRA-GRAD="" NOME-ORIENTADOR-GRAD=""/>
                <ENSINO-MEDIO-SEGUNDO-GRAU SEQUENCIA-FORMACAO="1" NIVEL="C" CODIGO-INSTITUICAO="JCPM00000007" NOME-INSTITUICAO="Fundação de Apoio à Escola Técnica do Estado do Rio de Janeiro" STATUS-DO-CURSO="CONCLUIDO" ANO-DE-INICIO="2015" ANO-DE-CONCLUSAO="2017"/>
            </FORMACAO-ACADEMICA-TITULACAO>
            <ATUACOES-PROFISSIONAIS>
                <ATUACAO-PROFISSIONAL CODIGO-INSTITUICAO="000500000000" NOME-INSTITUICAO="Universidade Federal Fluminense" SEQUENCIA-ATIVIDADE="1" SEQUENCIA-IMPORTANCIA="1">
                    <VINCULOS SEQUENCIA-HISTORICO="1" TIPO-DE-VINCULO="LIVRE" ENQUADRAMENTO-FUNCIONAL="LIVRE" CARGA-HORARIA-SEMANAL="12" FLAG-DEDICACAO-EXCLUSIVA="NAO" MES-INICIO="08" ANO-INICIO="2019" MES-FIM="12" ANO-FIM="2019" OUTRAS-INFORMACOES="" FLAG-VINCULO-EMPREGATICIO="SIM" OUTRO-VINCULO-INFORMADO="Bolsista" OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO="Monitor de disciplina" OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO-INGLES="" OUTRAS-INFORMACOES-INGLES=""/>
                </ATUACAO-PROFISSIONAL>
                <ATUACAO-PROFISSIONAL CODIGO-INSTITUICAO="000100000991" NOME-INSTITUICAO="LEVE Consultoria e Gestão de Projetos" SEQUENCIA-ATIVIDADE="2" SEQUENCIA-IMPORTANCIA="2">
                    <VINCULOS SEQUENCIA-HISTORICO="1" TIPO-DE-VINCULO="LIVRE" ENQUADRAMENTO-FUNCIONAL="LIVRE" CARGA-HORARIA-SEMANAL="4" FLAG-DEDICACAO-EXCLUSIVA="NAO" MES-INICIO="01" ANO-INICIO="2020" MES-FIM="06" ANO-FIM="2020" OUTRAS-INFORMACOES="" FLAG-VINCULO-EMPREGATICIO="SIM" OUTRO-VINCULO-INFORMADO="Voluntário" OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO="Membro de Empresa Júnior" OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO-INGLES="" OUTRAS-INFORMACOES-INGLES=""/>
                </ATUACAO-PROFISSIONAL>
            </ATUACOES-PROFISSIONAIS>
            <IDIOMAS>
                <IDIOMA IDIOMA="EN" DESCRICAO-DO-IDIOMA="Inglês" PROFICIENCIA-DE-LEITURA="BEM" PROFICIENCIA-DE-FALA="BEM" PROFICIENCIA-DE-ESCRITA="BEM" PROFICIENCIA-DE-COMPREENSAO="BEM"/>
                <IDIOMA IDIOMA="ES" DESCRICAO-DO-IDIOMA="Espanhol" PROFICIENCIA-DE-LEITURA="BEM" PROFICIENCIA-DE-FALA="RAZOAVELMENTE" PROFICIENCIA-DE-ESCRITA="RAZOAVELMENTE" PROFICIENCIA-DE-COMPREENSAO="RAZOAVELMENTE"/>
                <IDIOMA IDIOMA="IT" DESCRICAO-DO-IDIOMA="Italiano" PROFICIENCIA-DE-LEITURA="POUCO" PROFICIENCIA-DE-FALA="POUCO" PROFICIENCIA-DE-ESCRITA="POUCO" PROFICIENCIA-DE-COMPREENSAO="POUCO"/>
            </IDIOMAS>
        </DADOS-GERAIS>
        <PRODUCAO-BIBLIOGRAFICA/>
        <PRODUCAO-TECNICA/>
        <OUTRA-PRODUCAO/>
        <DADOS-COMPLEMENTARES>
            <INFORMACOES-ADICIONAIS-INSTITUICOES>
                <INFORMACAO-ADICIONAL-INSTITUICAO CODIGO-INSTITUICAO="000100000991" SIGLA-INSTITUICAO="LEVE" SIGLA-UF-INSTITUICAO="RJ" SIGLA-PAIS-INSTITUICAO="BRA" NOME-PAIS-INSTITUICAO="Brasil" FLAG-AGENCIA-FOMENTO="NAO" FLAG-INSTITUICAO-DE-ENSINO="NAO"/>
                <INFORMACAO-ADICIONAL-INSTITUICAO CODIGO-INSTITUICAO="000500000000" SIGLA-INSTITUICAO="UFF" SIGLA-UF-INSTITUICAO="RJ" SIGLA-PAIS-INSTITUICAO="BRA" NOME-PAIS-INSTITUICAO="Brasil" FLAG-AGENCIA-FOMENTO="NAO" FLAG-INSTITUICAO-DE-ENSINO="SIM"/>
                <INFORMACAO-ADICIONAL-INSTITUICAO CODIGO-INSTITUICAO="JCPM00000007" SIGLA-INSTITUICAO="FAETEC" SIGLA-UF-INSTITUICAO="RJ" SIGLA-PAIS-INSTITUICAO="BRA" NOME-PAIS-INSTITUICAO="Brasil" FLAG-AGENCIA-FOMENTO="NAO" FLAG-INSTITUICAO-DE-ENSINO="SIM"/>
            </INFORMACOES-ADICIONAIS-INSTITUICOES>
            <INFORMACOES-ADICIONAIS-CURSOS>
                <INFORMACAO-ADICIONAL-CURSO CODIGO-CURSO="60092360" CODIGO-ORGAO="" NOME-ORGAO="" CODIGO-INSTITUICAO="000500000000" NOME-INSTITUICAO="Universidade Federal Fluminense" NOME-GRANDE-AREA-DO-CONHECIMENTO="OUTROS" NOME-DA-AREA-DO-CONHECIMENTO="" NOME-DA-SUB-AREA-DO-CONHECIMENTO="" NOME-DA-ESPECIALIDADE="" NIVEL-CURSO="GRADUACAO"/>
            </INFORMACOES-ADICIONAIS-CURSOS>
        </DADOS-COMPLEMENTARES>
    </CURRICULO-VITAE>
   """.encode(
        "ISO-8859-1"
    )


@pytest.fixture
def create_test_zip():
    """Factory para criar arquivos ZIP de testes"""

    def _create_zip(zip_path: Path, files_data: dict):
        """
        Cria um arquivo ZIP com os dados fornecidos.

        Args:
            zip_path: Caminho onde criar o ZIP
            files_data: Dict {nome_arquivo: conteúdo_bytes}
        """

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename, content in files_data.items():
                zf.writestr(filename, content)

        return zip_path

    return _create_zip


@pytest.fixture
def mock_logger():
    """Mock para logger"""
    with patch("core.lattes_zip_processor.get_logger") as mock_get_logger:
        mock_logger_instance = Mock()
        mock_get_logger.return_value = mock_logger_instance
        yield mock_logger_instance
